### PR TITLE
chore: enable snow

### PR DESCRIPTION
**Pull request by iProdigy**
https://twitter.com/squidfunk/status/1597939243090788352

### CODE REVIEW

**Review by Felanbird — APPROVED** [review]

**Review by ALazyMeme — APPROVED** [review]

**Comment by iProdigy** [comment]
since the meta plugin is paywalled, this only applies snow if users load index first

if, instead, people open a different page (e.g., via bookmark), no snow will be loaded. happy to fix this though, just need to define the attribute on all *.md files

**Comment by pajlada** [comment]
I find the snow effect to be a bit too distracting while reading, so unless anyone has super strong opinions about needing snow I'd rather not merge this PR in

**Comment by Mm2PL** [comment]
Why do we need random shit flying over the screen on an information page again?

**Comment by iProdigy** [comment]
fair 👍

**Pull request closed without merging**
