### PR TITLE
Add documentation for `badges:` and `subtier:` search options

### PR DESCRIPTION
**Pull request by pajlada**
Feature added in https://github.com/Chatterino/chatterino2/pull/4013

### CODE REVIEW

**Comment by pajlada** [comment]
@1xelerate could you have a look as well since you made the feature?

**Comment by pajlada** [comment]
@xel86 can you take a look since you implemented the feature?

**Comment by xel86** [comment]
> @xel86 can you take a look since you implemented the feature?

looks good to me, only suggestion would be to add list of all possible badge key's since some of them can be kind of tricky to figure out only from their tooltip display name. You posted this snippet in chat:

`curl 'https://badges.twitch.tv/v1/badges/global/display?language=en' | jq '.badge_sets | keys'`

in a separate PR that I could look into we could maybe add a table for this

**Comment by pajlada** [comment]
> > @xel86 can you take a look since you implemented the feature?
> 
> looks good to me, only suggestion would be to add list of all possible badge key's since some of them can be kind of tricky to figure out only from their tooltip display name. You posted this snippet in chat:
> 
> `curl 'https://badges.twitch.tv/v1/badges/global/display?language=en' | jq '.badge_sets | keys'`
> 
> In a separate PR, that I could look into, we could maybe add a table for this

The list of badges should be in a shared space as we reference badges by their IDs in other places like filters

**Review by Felanbird — APPROVED** [review]

**Pull request merged**
